name: Simba
options:
  deploymentTarget:
    iOS: "17.0"
  bundleIdPrefix: com.simba
  xcodeVersion: "15.0"
settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: 5.9
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    GENERATE_INFOPLIST_FILE: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    TARGETED_DEVICE_FAMILY: 1
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
targets:
  Simba:
    type: application
    platform: iOS
    sources:
      - Simba
    dependencies:
      - package: GoogleSignIn
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bb.simba.app
        PRODUCT_NAME: Simba
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        INFOPLIST_KEY_CFBundleDisplayName: Simba
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    info:
      path: Simba/Info.plist
      properties:
        CFBundleDisplayName: Simba
        UILaunchScreen: {}
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLSchemes:
              - com.googleusercontent.apps.350262483118-bcrf17c6jrkfrum041she8njri3ju6m1
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        BGTaskSchedulerPermittedIdentifiers:
          - com.bb.simba.app.refresh
        UIBackgroundModes:
          - fetch
  SimbaTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - SimbaTests
    dependencies:
      - target: Simba
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bb.simba.tests
        SWIFT_VERSION: 5.9
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: 7.0.0
